name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # roz midnight ko run hoga
  workflow_dispatch:       # manually bhi run kar sakte ho
  push:
    branches:
      - main             # jab main pe push karo tab bhi run hoga

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: DhirajBhavsar9900
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          commit_message: "Update snake animation [skip ci]"
